#!/usr/bin/env python3
"""OpenLoad genconfig — .config → C header + CMake fragment.

从 Kconfig .config 生成:
  - openload_autoconfig.h  (C #define 块)
  - openload_kconfig.cmake (CMake set() 块)

用法:
    python tools/genconfig.py <path/to/.config> --out-dir <build-dir>

示例:
    python tools/genconfig.py examples/stm32f103zet6_gcc/.config --out-dir build/kconfig
"""
import argparse
import sys
from pathlib import Path
from kconfiglib import Kconfig, BOOL, INT, HEX, STRING


def emit_header(kconf, out_path):
    """生成 C 头文件 openload_autoconfig.h."""
    lines = [
        '/* AUTO-GENERATED by tools/genconfig.py — DO NOT EDIT */',
        '#pragma once',
        '',
    ]

    # 枚举所有 OPENLOAD_* 符号
    for sym in kconf.unique_defined_syms:
        if not sym.name.startswith('OPENLOAD_'):
            continue

        # choice 的子选项不直接 emit (后面单独处理 choice 块)
        if sym.choice:
            continue

        if sym.type == BOOL:
            val = 1 if sym.tri_value == 2 else 0  # tri_value: 0=n, 1=m, 2=y
            lines.append(f'#define {sym.name} {val}')

        elif sym.type in (INT, HEX):
            lines.append(f'#define {sym.name} {sym.str_value}')

        elif sym.type == STRING:
            val = sym.str_value
            # 特殊处理: AES_KEY / ED25519_PUBKEY 转 C byte array 元素串
            # 不包花括号 — 调用点形如:
            #     static const uint8_t k[16] = { OPENLOAD_AES_KEY_BYTES };
            # 自己加外层 { }
            if sym.name in ('OPENLOAD_AES_KEY', 'OPENLOAD_ED25519_PUBKEY'):
                if len(val) % 2 != 0:
                    print(f"warning: {sym.name} hex string length not even, padding with 0",
                          file=sys.stderr)
                    val += '0'
                hex_pairs = ', '.join(f'0x{val[i:i+2]}' for i in range(0, len(val), 2))
                lines.append(f'#define {sym.name}_BYTES {hex_pairs}')
            # 特殊处理: CLI_PASSWORD 空串 → ((const char *)0)
            elif sym.name == 'OPENLOAD_CLI_PASSWORD' and val == '':
                lines.append(f'#define {sym.name} ((const char *)0)')
            else:
                # 普通字符串: 转义 \ 和 "
                escaped = val.replace('\\', '\\\\').replace('"', '\\"')
                lines.append(f'#define {sym.name} "{escaped}"')

    lines.append('')

    # 处理 choice 块: 转回原 enum int
    # UPGRADE_STRATEGY choice → #define OPENLOAD_UPGRADE_STRATEGY 1/2/3/4
    strategy_map = {
        'OPENLOAD_UPGRADE_STRATEGY_SINGLE_BANK': 1,
        'OPENLOAD_UPGRADE_STRATEGY_STAGING': 2,
        'OPENLOAD_UPGRADE_STRATEGY_STAGING_BACKUP': 3,
        'OPENLOAD_UPGRADE_STRATEGY_DUAL_BANK': 4,
    }
    for child_name, enum_val in strategy_map.items():
        sym = kconf.syms.get(child_name)
        if sym and sym.tri_value == 2:  # 选中
            lines.append(f'#define OPENLOAD_UPGRADE_STRATEGY {enum_val}')
            break

    # RECOVERY_POLICY choice → #define OPENLOAD_RECOVERY_POLICY 1/2/3
    policy_map = {
        'OPENLOAD_RECOVERY_POLICY_CLI': 1,
        'OPENLOAD_RECOVERY_POLICY_HANG': 2,
        'OPENLOAD_RECOVERY_POLICY_ROLLBACK': 3,
    }
    for child_name, enum_val in policy_map.items():
        sym = kconf.syms.get(child_name)
        if sym and sym.tri_value == 2:
            lines.append(f'#define OPENLOAD_RECOVERY_POLICY {enum_val}')
            break

    lines.append('')
    out_path.write_text('\n'.join(lines), encoding='utf-8')


def emit_cmake(kconf, out_path):
    """生成 CMake fragment openload_kconfig.cmake."""
    lines = ['# AUTO-GENERATED by tools/genconfig.py — DO NOT EDIT', '']

    # 所有 OPENLOAD_ENABLE_* bool 选项 → CMake cache var
    for sym in kconf.unique_defined_syms:
        if sym.type != BOOL:
            continue
        if not sym.name.startswith('OPENLOAD_ENABLE_'):
            continue
        val = 'ON' if sym.tri_value == 2 else 'OFF'
        lines.append(f'set({sym.name} {val} CACHE BOOL "" FORCE)')

    # 特殊: OPENLOAD_ENABLE_ESP8266 同步到 port cache var (F1 + F4 双轨)
    esp_sym = kconf.syms.get('OPENLOAD_ENABLE_ESP8266')
    if esp_sym and esp_sym.type == BOOL:
        val = 'ON' if esp_sym.tri_value == 2 else 'OFF'
        lines.append(f'set(STM32F1_PORT_ENABLE_ESP8266 {val} CACHE BOOL "" FORCE)')
        lines.append(f'set(STM32F4_PORT_ENABLE_ESP8266 {val} CACHE BOOL "" FORCE)')

    lines.append('')
    out_path.write_text('\n'.join(lines), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description='Generate C header + CMake from .config')
    parser.add_argument('config', help='Path to .config file')
    parser.add_argument('--out-dir', required=True, help='Output directory')
    args = parser.parse_args()

    config_path = Path(args.config)
    if not config_path.exists():
        print(f"error: .config not found: {config_path}", file=sys.stderr)
        sys.exit(1)

    out_dir = Path(args.out_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    # 加载 Kconfig (假设在 repo 根)
    repo_root = Path(__file__).parent.parent
    kconf = Kconfig(str(repo_root / 'Kconfig'))
    kconf.load_config(str(config_path))

    # 生成两个输出文件
    emit_header(kconf, out_dir / 'openload_autoconfig.h')
    emit_cmake(kconf, out_dir / 'openload_kconfig.cmake')

    print(f"Generated: {out_dir / 'openload_autoconfig.h'}")
    print(f"Generated: {out_dir / 'openload_kconfig.cmake'}")


if __name__ == '__main__':
    main()
