#!/usr/bin/env python3
"""OpenLoad migrate_config — 现有 openload_config.h → .config 一次性迁移.

扫描现有 openload_config.h 中的 #define, 转成 Kconfig .config 格式.

用法:
    python tools/migrate_config.py <openload_config.h> -o <output.config>

示例:
    python tools/migrate_config.py examples/stm32f103zet6_gcc/openload_config.h \\
        -o examples/stm32f103zet6_gcc/.config
"""
import argparse
import re
import sys
from pathlib import Path
from kconfiglib import Kconfig, BOOL, INT, HEX, STRING


# 匹配 #define OPENLOAD_XXX <value>
DEFINE_RE = re.compile(
    r'^\s*#define\s+(OPENLOAD_\w+)\s+(.+?)(?://.*)?$',
    re.MULTILINE
)

# 匹配 byte array literal (可能跨多行)
# 例: { 0x4F, 0x70, ... }
ARRAY_RE = re.compile(
    r'\{\s*((?:0x[0-9a-fA-F]{2}\s*,?\s*)+)\}',
    re.DOTALL
)


def parse_header(header_path, kconf):
    """解析 openload_config.h, 返回 {sym_name: value_str} 字典."""
    text = header_path.read_text(encoding='utf-8')
    config = {}

    # 特殊: 先处理 AES_KEY_BYTES / ED25519_PUBKEY_BYTES (可能跨多行)
    for key_name in ('OPENLOAD_AES_KEY', 'OPENLOAD_ED25519_PUBKEY'):
        if key_name not in kconf.syms:
            continue
        array_name = f'{key_name}_BYTES'
        # 匹配 #define ARRAY_NAME \ <newline> 0xXX,0xYY,... (跨多行, 用 \ 续行)
        # 策略: 找到 #define 行, 然后向后收集所有以 \ 结尾的续行
        # 正则: #define NAME 后面跟任意内容直到遇到不以 \ 结尾的行
        array_pattern = rf'#define\s+{re.escape(array_name)}\s+(.*?)(?:\n(?![ \t])|\Z)'
        array_match = re.search(array_pattern, text, re.DOTALL)
        if array_match:
            # 去掉续行符 \ 和换行, 保留 hex bytes
            array_content = array_match.group(1).replace('\\', ' ').replace('\n', ' ')
            hex_bytes = re.findall(r'0x([0-9a-fA-F]{2})', array_content)
            config[key_name] = ''.join(hex_bytes).upper()
        else:
            print(f"warning: {array_name} not found, using empty", file=sys.stderr)
            config[key_name] = ''

    for match in DEFINE_RE.finditer(text):
        name = match.group(1)
        val_raw = match.group(2).strip()

        # 跳过不在 Kconfig 中的符号
        if name not in kconf.syms:
            continue

        # 跳过已处理的 key 字段
        if name in ('OPENLOAD_AES_KEY', 'OPENLOAD_ED25519_PUBKEY'):
            continue

        sym = kconf.syms[name]

        # bool: 1 → y, 0 → n
        if sym.type == BOOL:
            if val_raw in ('1', 'true', 'TRUE'):
                config[name] = 'y'
            else:
                config[name] = 'n'

        # int / hex: 原样
        elif sym.type in (INT, HEX):
            config[name] = val_raw

        # string: 去掉引号 (如果有)
        elif sym.type == STRING:
            # 特殊: CLI_PASSWORD = ((const char *)0) → 空串
            if name == 'OPENLOAD_CLI_PASSWORD' and '(const char *)0' in val_raw:
                config[name] = ''
            else:
                # 去掉首尾引号
                if val_raw.startswith('"') and val_raw.endswith('"'):
                    val_raw = val_raw[1:-1]
                # 反转义 \" 和 \\
                val_raw = val_raw.replace('\\"', '"').replace('\\\\', '\\')
                config[name] = val_raw

    return config


def write_config(kconf, config_dict, out_path):
    """写 .config 文件 (Kconfig 格式)."""
    lines = ['# AUTO-GENERATED by tools/migrate_config.py', '']

    for sym in kconf.unique_defined_syms:
        if not sym.name.startswith('OPENLOAD_'):
            continue

        # choice 子选项不直接写 (由 choice 块处理)
        if sym.choice:
            continue

        val = config_dict.get(sym.name)
        if val is None:
            # 未在 header 中定义, 用 Kconfig 默认值
            if sym.type == BOOL:
                val = 'y' if sym.tri_value == 2 else 'n'
            elif sym.type in (INT, HEX):
                val = sym.str_value
            elif sym.type == STRING:
                val = sym.str_value

        # kconfiglib 期望 CONFIG_ 前缀, 但我们的符号已含 OPENLOAD_ 前缀
        # 所以写成 CONFIG_OPENLOAD_XXX=y 格式
        config_name = f'CONFIG_{sym.name}'

        if sym.type == BOOL:
            if val == 'y':
                lines.append(f'{config_name}=y')
            else:
                lines.append(f'# {config_name} is not set')
        elif sym.type in (INT, HEX):
            lines.append(f'{config_name}={val}')
        elif sym.type == STRING:
            # 字符串用引号包裹
            lines.append(f'{config_name}="{val}"')

    # 处理 choice 块: 从 OPENLOAD_UPGRADE_STRATEGY / OPENLOAD_RECOVERY_POLICY 反推
    strategy_val = config_dict.get('OPENLOAD_UPGRADE_STRATEGY', '2')
    strategy_map = {
        '1': 'OPENLOAD_UPGRADE_STRATEGY_SINGLE_BANK',
        '2': 'OPENLOAD_UPGRADE_STRATEGY_STAGING',
        '3': 'OPENLOAD_UPGRADE_STRATEGY_STAGING_BACKUP',
        '4': 'OPENLOAD_UPGRADE_STRATEGY_DUAL_BANK',
    }
    selected = strategy_map.get(strategy_val, 'OPENLOAD_UPGRADE_STRATEGY_STAGING')
    for child_name in strategy_map.values():
        config_name = f'CONFIG_{child_name}'
        if child_name == selected:
            lines.append(f'{config_name}=y')
        else:
            lines.append(f'# {config_name} is not set')

    policy_val = config_dict.get('OPENLOAD_RECOVERY_POLICY', '1')
    policy_map = {
        '1': 'OPENLOAD_RECOVERY_POLICY_CLI',
        '2': 'OPENLOAD_RECOVERY_POLICY_HANG',
        '3': 'OPENLOAD_RECOVERY_POLICY_ROLLBACK',
    }
    selected = policy_map.get(policy_val, 'OPENLOAD_RECOVERY_POLICY_CLI')
    for child_name in policy_map.values():
        config_name = f'CONFIG_{child_name}'
        if child_name == selected:
            lines.append(f'{config_name}=y')
        else:
            lines.append(f'# {config_name} is not set')

    lines.append('')
    out_path.write_text('\n'.join(lines), encoding='utf-8')


def main():
    parser = argparse.ArgumentParser(description='Migrate openload_config.h to .config')
    parser.add_argument('header', help='Path to openload_config.h')
    parser.add_argument('-o', '--output', required=True, help='Output .config path')
    args = parser.parse_args()

    header_path = Path(args.header)
    if not header_path.exists():
        print(f"error: header not found: {header_path}", file=sys.stderr)
        sys.exit(1)

    out_path = Path(args.output)

    # 加载 Kconfig (假设在 repo 根)
    repo_root = Path(__file__).parent.parent
    kconf = Kconfig(str(repo_root / 'Kconfig'))

    # 解析 header
    config_dict = parse_header(header_path, kconf)

    # 写 .config
    write_config(kconf, config_dict, out_path)

    print(f"Migrated: {header_path} → {out_path}")


if __name__ == '__main__':
    main()
